CREATE DATABASE delilah_resto;

CREATE TABLE PEDIDOS(
ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
ESTADO VARCHAR(20) NOT NULL,
HORA DATETIME NOT NULL,
DESCRIPCION VARCHAR(150) NOT NULL,
METODO_PAGO VARCHAR(20) NOT NULL,
ID_USUARIO INT NOT NULL,
TOTAL FLOAT NOT NULL);

CREATE TABLE USUARIOS (
ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_USUARIO VARCHAR(50) NOT NULL,
NOMBRE_APELLIDO VARCHAR(60) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
TELEFONO INT NOT NULL,
DIRECCION VARCHAR(60) NOT NULL,
PASSWORD VARCHAR(20) NOT NULL,
ES_ADMIN BOOLEAN DEFAULT FALSE);

CREATE TABLE PRODUCTOS (
ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) NOT NULL,
PRECIO_UNITARIO FLOAT NOT NULL,
URL_IMAGEN VARCHAR(60) NOT NULL,
DESCRIPCION VARCHAR(150) NOT NULL);

CREATE TABLE DETALLE_PEDIDO(
ID_PRODUCTO INT,
ID_PEDIDO INT,
CANTIDAD_PRODUCTO INT NOT NULL DEFAULT 1,
PRIMARY KEY(ID_PRODUCTO, ID_PEDIDO));

ALTER TABLE PEDIDOS ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO);
ALTER TABLE DETALLE_PEDIDO ADD FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO);
ALTER TABLE DETALLE_PEDIDO ADD FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO); 

INSERT INTO USUARIOS VALUES (NULL, 'javi', 'javier acuna', 'javi@gmail.com', 4533291, 'celestino 23', 'javi123', true);
INSERT INTO USUARIOS VALUES (NULL, 'eze', 'ezequiel dominguez', 'eze.domi@gmail.com', 4523231, 'av. colon 2', 'ezequ1el', false);
INSERT INTO USUARIOS VALUES (NULL, 'pablo', 'pablo lopez', 'lopezpablo@gmail.com', 4522134, 'felix frias 89', 'L0p3z', false);

INSERT INTO PRODUCTOS VALUES(NULL,'HAMBURGUESA', 200,'https://via.placeholder.com/200','HAMBURGUESA CON PAPAS FRITAS');
INSERT INTO PRODUCTOS VALUES(NULL,'PIZZA', 280,'https://via.placeholder.com/250','PIZZA NAPOLITANA');
INSERT INTO PRODUCTOS VALUES(NULL,'LOMO', 350,'https://via.placeholder.com/300','LOMO COMPLETO');

INSERT INTO PEDIDOS VALUES (NULL, 'ENVIADO', NOW(), 'PIZZA','EFECTIVO', 1, 300);
INSERT INTO PEDIDOS VALUES (NULL, 'NUEVO', NOW(), 'HAMBURGUESA x2', 'PAGO ONLINE', 2, 300);
INSERT INTO PEDIDOS VALUES (NULL, 'NUEVO', NOW(), 'LOMO x4', 'EFECTIVO', 2, 800);

INSERT INTO DETALLE_PEDIDO VALUES(1, 1, 1);
INSERT INTO DETALLE_PEDIDO VALUES(2, 2, 2);
INSERT INTO DETALLE_PEDIDO VALUES(3, 3, 4);